version: "3.0"

intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy
  - bot_challenge
  - faq
    use_entities: true

entities:
- condition

slots:
  condition:
    type: rasa.shared.core.slots.TextSlot
    initial_value: null
    auto_fill: true
    influence_conversation: false

responses:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great, carry on!"

  utter_goodbye:
  - text: "Bye"

  utter_iamabot:
  - text: "I am a bot, powered by Rasa."

  utter_ask_age_group:
  - text: "Please select the category for which you want to view the symptoms of ?"
    buttons: 
      - title: "common"
        payload: "Symptoms(common)"
      - title: "babies/infants"
        payload: "Symptoms(babies/infants)"
      - title: "old people"
        payload: "Symptoms(old people)"
      - title: "male"
        payload: "Symptoms(male)"
      - title: "female"
        payload: "Symptoms(female)"
      - title: "critical_stage"
        payload: "Symptoms (critical_stage)"

  

actions:
- '...'
- query_resource
- utter_ask_age_group
- utter_greet
- utter_iamabot

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
