# This file contains the credentials for the voice & chat platforms
# which your bot is using.
# https://rasa.com/docs/rasa/messaging-and-voice-channels

rest:
#  # you don't need to provide anything here - this channel doesn't
#  # require any credentials


#facebook:
#  verify: "<verify>"
#  secret: "<your secret>"
#  page-access-token: "<your page access token>"

slack:
  slack_token: "xoxb-3520459090356-3541894619008-pjZvXVP0DEd7iJwBJEw7IJ34"
  slack_channel: 
  slack_signing_secret: "bb05a400a0b30f9baa5508870b903861"

telegram:
  access_token: "5577228744:AAGMczaitBxKHqjHMfkvHh6vWqURPRYwypE"
  verify: "hyd_medibot"
  webhook_url: "https://85aa-106-215-20-11.in.ngrok.io/webhooks/telegram/webhook"

twilio:
  account_sid: "AC856106f472e9dce58e7997750d6db2e8"
  auth_token: "6e7bc02c1252f6193aa54050acacc8bb" 
  twilio_number: "whatsapp:+14155238886"

socketio:
  user_message_evt: user_uttered
  bot_message_evt: bot_uttered
  session_persistence: true

#mattermost:
#  url: "https://<mattermost instance>/api/v4"
#  token: "<bot token>"
#  webhook_url: "<callback URL>"

# This entry is needed if you are using Rasa X. The entry represents credentials
# for the Rasa X "channel", i.e. Talk to your bot and Share with guest testers.
rasa:
  url: "http://localhost:5002/api"
