version: '3.0'
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
intents:
- greet
- inform
- subscribe
- FAQS
- Goodbye
- Diabetes

entities:
- disease

slots:
  email:
    type: text
    influence_conversation: false
    mappings: []
  disease:
    type: text
    influence_conversation: true
    mappings: []
  disease_type:
    type: text


responses:
  utter_greet:
  - text: |
      Hello! How can I help you?
  - text: |
      Hi!
  utter_ask_email:
  - text: |
      What is your email address?
  utter_subscribed:
  - text: |
      Check your inbox at {email} in order to finish subscribing to the newsletter!
  - text: You're all set! Check your inbox at {email} to confirm your subscription.

  utter_bye:
  - text: |
      Bye! Have a nice day!

  utter_FAQS:
  - text: |
      The most important part of managing {disease} is your diet 



actions:
- '...'
- utter_greet
- utter_medicine
- utter_FAQS


forms:
  newsletter_form:
    required_slots:
    - email
